[package]
name = "av-metrics-tool"
version = "0.2.1"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
edition = "2018"
description = "A CLI tool for measuring audio/video metrics"
license = "MIT"
repository = "https://github.com/rust-av/av-metrics"

[dependencies]
av-metrics = "0.2"
clap = "2.33"
y4m = "0.4"
